$NetBSD$

--- ../librespot/connect/Cargo.toml.orig	2019-03-21 16:21:20.000000000 +0000
+++ ../librespot/connect/Cargo.toml
@@ -29,7 +29,8 @@ aes-ctr = "0.3.0"
 block-modes = "0.2.0"
 
 dns-sd = { version = "0.1.3", optional = true }
-mdns = { git = "https://github.com/plietar/rust-mdns", optional = true }
+#mdns = { git = "https://github.com/plietar/rust-mdns", optional = true }
+mdns = { path = "../../rust-mdns", optional = true }
 
 [features]
 default = ["mdns"]
