$NetBSD$

--- Cargo.toml.orig	2019-11-03 15:53:48.000000000 +0000
+++ Cargo.toml
@@ -24,7 +24,7 @@ serde = { version = "1.0.99", features =
 serde_ini = "0.2.0"
 sha-1 = "0.8"
 simplelog = "0.7"
-structopt = { git = "https://github.com/TeXitoi/structopt/", rev = "0c888e962d842f2c90c6c290d3a2a40947b37005", features = ["color"] }
+structopt = { path = "../structopt", features = ["color"] }
 syslog = "4.0.1"
 tokio-core = "0.1"
 tokio-io = "0.1"
@@ -35,7 +35,7 @@ whoami = "0.5.3"
 [dependencies.librespot]
 default-features = false
 features = ["with-tremor"]
-git = "https://github.com/librespot-org/librespot.git"
+path = "../librespot"
 
 [dev-dependencies]
 env_logger = "0.7"
