$NetBSD$

--- ../rust-mdns/Cargo.toml.orig	2018-12-19 13:58:45.000000000 +0000
+++ ../rust-mdns/Cargo.toml
@@ -20,7 +20,8 @@ nix = "0.11"
 rand = "0.5"
 tokio-core = "0.1"
 
-dns-parser = { git = "https://github.com/plietar/dns-parser" }
+#dns-parser = { git = "https://github.com/plietar/dns-parser" }
+dns-parser = { path = "../dns-parser" }
 
 [target.'cfg(windows)'.dependencies]
 winapi = "0.2.8"
