$NetBSD$

--- ../librespot/audio/Cargo.toml.orig	2019-03-21 16:21:20.000000000 +0000
+++ ../librespot/audio/Cargo.toml
@@ -17,7 +17,8 @@ num-traits = "0.1.36"
 tempfile = "2.1"
 aes-ctr = "0.3.0"
 
-tremor = { git = "https://github.com/plietar/rust-tremor", optional = true }
+#tremor = { git = "https://github.com/plietar/rust-tremor", optional = true }
+tremor = { path = "../../rust-tremor", optional = true }
 vorbis = { version ="0.1.0", optional = true }
 
 [features]
